name: CI

on: [push, pull_request]

env:
  PARTIELS_URL: https://github.com/Ircam-Partiels/Partiels/releases/download
  PARTIELS_VERSION: 2.0.10

jobs:
  Format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 isort
    - name: Check code formatting with Black
      run: black --check .
    - name: Check import order with isort
      run: isort . --check --diff
    - name: Run Flake8
      run: flake8 src tests

  Ubuntu:
    runs-on: ubuntu-22.04
    needs: Format
    steps:
    - uses: actions/checkout@v4
    - name: Prepare
      run: sudo apt update && sudo apt install -y unzip wget
    - name: Download and install Partiels binary
      run: |
        wget $PARTIELS_URL/$PARTIELS_VERSION/Partiels-Linux.tar.gz
        tar -xzf Partiels-Linux.tar.gz
        sh Partiels/Partiels-install.sh
    - name: Upgrade pip and setuptools
      run: python -m pip install --upgrade pip setuptools
    - name: Install dependencies
      run: pip install pytest build
    - name: Build PartielsPy
      run: python -m build
    - name: Install PartielsPy
      run: pip install dist/*.whl
    - name: Run tests
      run: pytest -s tests/

  Windows:
    runs-on: windows-latest
    needs: Format
    steps:
      - uses: actions/checkout@v4
      - name: Download and install Partiels binary
        shell: powershell
        run: |
          Invoke-WebRequest -Uri $env:PARTIELS_URL/$env:PARTIELS_VERSION/Partiels-Windows.exe -OutFile "Partiels-Windows.exe"
          $signature = Get-AuthenticodeSignature .\Partiels-Windows.exe
          if ($signature.Status -ne 'Valid') {
            throw "The installer isn't signed or the signature is invalid"
          }
          $proc = Start-Process .\Partiels-Windows.exe -ArgumentList "/VERYSILENT /NORESTART /SP-" -Wait -PassThru
          if ($proc.ExitCode -ne 0) {
            throw "The installation failed with the exit code $($proc.ExitCode)"
          }
      - name: Upgrade pip and setuptools
        run: python -m pip install --upgrade pip setuptools
      - name: Install dependencies
        run: pip install pytest build
      - name: Build PartielsPy
        run: python -m build
      - name: Install PartielsPy
        shell: powershell
        run: Get-ChildItem -Path dist\*.whl | ForEach-Object { pip install $_.FullName }
      - name: Run tests
        run: pytest -s tests/
  
  MacOS:
    runs-on: macos-latest
    needs: Format
    steps:
      - uses: actions/checkout@v4
      - name: Download and install Partiels binary
        shell: bash
        run: |
          curl -L -v -o Partiels-MacOS.dmg $PARTIELS_URL/$PARTIELS_VERSION/Partiels-MacOS.dmg
          MOUNT_DIR=$(hdiutil attach Partiels-MacOS.dmg | grep Volumes | awk '{print $3}')
          cp -r "$MOUNT_DIR/Partiels.app" /Applications/
      - name: Upgrade pip and setuptools
        run: python -m pip install --upgrade pip setuptools
      - name: Install dependencies
        run: pip install pytest build
      - name: Build PartielsPy
        run: python -m build
      - name: Install PartielsPy
        run: pip install dist/*.whl
      - name: Run tests
        run: pytest -s tests/

  Doc:
    runs-on: ubuntu-latest
    needs: Format
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: pip install sphinx
    - name: Generate documentation
      run: |
        sphinx-apidoc -o ./docs ./src/PartielsPy ./src/PartielsPy/templates/*
        sphinx-build -b html ./docs ./docs/_build/html
    - name: Upload documentation as artifact
      uses: actions/upload-artifact@v4
      with:
        name: html-doc
        path: docs/_build/html
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html
